name:  Reporte de Bug
description: Informa de un error o comportamiento inesperado en la aplicaci贸n.
title: "[BUG] Descripci贸n concisa del problema"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por tomarte el tiempo de reportar este problema. Por favor, completa la siguiente informaci贸n para ayudarnos a reproducir y solucionar el error lo antes posible.

  - type: input
    id: version
    attributes:
      label: Versi贸n del Software
      description: 驴En qu茅 versi贸n o commit del proyecto encontraste el bug?
      placeholder: "Ej: v1.2.0 o commit hash"
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: Descripci贸n del Problema
      description: Describe claramente el problema.
      placeholder: "Ej: Al hacer clic en el bot贸n 'Guardar', la aplicaci贸n se congela en lugar de guardar los datos."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Pasos para Reproducir
      description: Enumera los pasos necesarios para recrear el comportamiento inesperado.
      placeholder: |
        1. Ir a 'P谩gina de Configuraci贸n'.
        2. Ingresar un valor de '0' en el campo 'L铆mite'.
        3. Hacer clic en 'Aplicar Cambios'.
        4. Observar el error.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Comportamiento Esperado
      description: Describe lo que *deber铆a* haber sucedido.
    validations:
      required: true

  - type: checkbox
    id: environment-details
    attributes:
      label: Entorno
      description: Por favor, especifica el entorno donde ocurri贸 el error.
      options:
        - label: SO: Windows
        - label: SO: macOS
        - label: SO: Linux
        - label: Navegador: Chrome
        - label: Navegador: Firefox
        - label: Navegador: Edge
        - label: Otros (Por favor, especifica en la descripci贸n)
        
  - type: textarea
    id: screenshots
    attributes:
      label: Capturas de Pantalla o Logs (Opcional)
      description: Adjunta capturas de pantalla o fragmentos de logs que puedan ser 煤tiles.