name: ✨ Solicitud de Característica (Feature Request)
description: Sugiere una idea para una nueva funcionalidad o mejora.
title: "[FEAT]: "
labels: ["enhancement", "feature"]
body:
  - type: markdown
    attributes:
      value: |
        ¡Nos encanta que propongas nuevas ideas! Describe tu propuesta lo más detalladamente posible.
  - type: textarea
    id: problema-actual
    attributes:
      label: ¿El problema que resuelve?
      description: Describe el problema o limitación actual que esta nueva funcionalidad abordaría.
      placeholder: "Actualmente, no hay una forma de..."
    validations:
      required: true
  - type: textarea
    id: solucion-propuesta
    attributes:
      label: Solución o Característica Propuesta
      description: Describe la solución o la nueva característica que sugieres. Sé detallado sobre cómo debería funcionar.
      placeholder: "Sugiero añadir un botón que haga lo siguiente..."
    validations:
      required: true
  - type: textarea
    id: alternativas
    attributes:
      label: Alternativas Consideradas
      description: Si has considerado soluciones o alternativas diferentes, descríbelas aquí.
    validations:
      required: false
  - type: checkboxes
    id: alcance
    attributes:
      label: ¿Es esta característica crítica?
      options:
        - label: Es una mejora menor y no bloquea el uso.
        - label: Es importante, pero hay soluciones temporales.
        - label: Es crucial y bloquea el uso o la adopción.
  - type: markdown
    attributes:
      value: |
        ¡Gracias por tu contribución!