<<<<<<< HEAD
name: ✨ Solicitud de Característica (Feature Request)
description: Sugiere una idea para una nueva funcionalidad o mejora.
title: "[FEAT]: "
labels: ["enhancement", "feature"]
=======
name: ✨ Solicitud de Funcionalidad
description: Sugiere una nueva idea o funcionalidad para el proyecto.
title: "[FEATURE] Breve descripción de la funcionalidad"
labels: ["enhancement", "triage"]

  - type: markdown
    attributes:
      value: |
<<<<<<< HEAD
        ¡Nos encanta que propongas nuevas ideas! Describe tu propuesta lo más detalladamente posible.
  - type: textarea
    id: problema-actual
    attributes:
      label: ¿El problema que resuelve?
      description: Describe el problema o limitación actual que esta nueva funcionalidad abordaría.
      placeholder: "Actualmente, no hay una forma de..."
    validations:
      required: true
  - type: textarea
    id: solucion-propuesta
    attributes:
      label: Solución o Característica Propuesta
      description: Describe la solución o la nueva característica que sugieres. Sé detallado sobre cómo debería funcionar.
      placeholder: "Sugiero añadir un botón que haga lo siguiente..."
    validations:
      required: true
  - type: textarea
    id: alternativas
    attributes:
      label: Alternativas Consideradas
      description: Si has considerado soluciones o alternativas diferentes, descríbelas aquí.
    validations:
      required: false
  - type: checkboxes
    id: alcance
    attributes:
      label: ¿Es esta característica crítica?
      options:
        - label: Es una mejora menor y no bloquea el uso.
        - label: Es importante, pero hay soluciones temporales.
        - label: Es crucial y bloquea el uso o la adopción.
  - type: markdown
    attributes:
      value: |
        ¡Gracias por tu contribución!
=======
        ¡Nos encantan las nuevas ideas! Por favor, describe la funcionalidad que te gustaría ver implementada.

  - type: textarea
    id: problem-to-solve
    attributes:
      label: El Problema o Necesidad
      description: Describe el problema o la necesidad del usuario que esta nueva funcionalidad resolvería. ¿Por qué es importante?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: La Solución Propuesta (Funcionalidad)
      description: Describe cómo te imaginas que funcionaría esta nueva característica. Si es posible, incluye ejemplos de uso o casos de borde.
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternativas Consideradas (Opcional)
      description: ¿Has considerado otras soluciones? Si es así, ¿por qué esta propuesta es mejor?
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Mockups o Ejemplos (Opcional)
      description: Adjunta un enlace o una imagen si tienes un mockup de cómo se vería o funcionaría.
>>>>>>> mi-primera-rama
